branches:
  except:
    - draft

language: node_js

node_js:
  - '8'
  - '9'
  - '10'

cache:
  directories:
    - $HOME/.pnpm-store
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node

install:
  - pnpm recursive link --shamefully-flatten
  - bash sh/ci/before-script.sh

script:
  - pnpm test -- --runInBand
  - pnpm run build

after_script:
  - bash sh/ci/after-script.sh
