branches:
  except:
    - draft

language: node_js

node_js:
  - 8
  - 9
  - 10

env:
  - COVERALLS=true

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries
    - $HOME/node_modules
    - node_modules

before_script:
  - chmod -R +x sh

install:
  - yarn

script:
  - travis_wait 240 yarn test
  - yarn run build
