branches:
  except:
    - draft

language: node_js

node_js:
  - '8'
  - '9'
  - '10'

env:
  - COVERALLS=true

cache:
  directories:
    - $HOME/.pnpm-store
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries

before_script:
  - chmod -R +x sh

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node

install:
  - pnpm recursive link --shamefully-flatten

jobs:
  include:
    - script: pnpm test -- --runInBand
    - script: pnpm run build
