setupTestFrameworkScriptFile: jest-extended
transform:
  '\.jsx?$': 'babel-jest'
  '\.tsx?$': 'ts-jest'
testRegex: (test|spec|check)\.(jsx?|tsx?)$
moduleFileExtensions:
  - ts
  - tsx
  - js
  - jsx
  - json
  - node
coveragePathIgnorePatterns:
  - /node_modules/
  - <rootDir>/check/
  - <rootDir>/test/
