projects:
  - displayName: standardjs
    runner: jest-runner-standard
    testMatch: ['<rootDir>/**/*.js']
    testPathIgnorePatterns:
      - /node_modules/
      - /coverage/
  - displayName: test
    transform:
      '\.jsx?$': 'babel-jest'
      '\.tsx?$': 'ts-jest'
      '\.(yaml|yml)$': 'yaml-jest'
    testRegex: \.(test|spec|check)\.(jsx?|tsx?)$
    moduleFileExtensions:
      - ts
      - tsx
      - js
      - jsx
      - json
      - node
    coveragePathIgnorePatterns:
      - /node_modules/
      - \/check\/
      - \/test\/
      - \/.polyfill\/
      - .*.json$
      - .*.yaml$
      - .*.yml$
    testEnvironment: node
    globals:
      ts-jest:
        diagnostics: false
        tsConfig:
          importHelpers: false
          target: es2017
          module: commonjs
          lib: [es2017, es2018, esnext]
          esModuleInterop: true
          experimentalDecorators: true
          noEmit: true
          strict: false
